import type { Metadata } from 'next';
import Header from '@/components/layout/SellerHeader';
import Footer from '@/components/layout/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div>
        {/* Sidebar */}
        {children}
      </div>
      <Footer />
    </>
  );
}
